# 1 Introduction
ในบทนี้เราจะเน้นที่ Library 2 ตัวคือ `Pandas` และ `NumPy` ซึ่งจะช่วยได้มากในการทำ Data Analysis

# 2 Gapminder Data

มี Data ให้ 5 Table

ด้วย Data ชุดนี้จะตอบคำถามอะไรได้บ้าง คิดมา 5 ข้อ

In [1]:
import unicodecsv

#read data from CSV file and make it to lists
def read_csv(filename):
    with open(filename, 'rb') as f:
        reader = unicodecsv.DictReader(f)
        return list(reader)

In [2]:
# 5 table
employment_levels = read_csv('../data/chapter2/employment_above_15.csv')
life_expectancy = read_csv('../data/chapter2/life_expectancy.csv')
gdp_per_capita = read_csv('../data/chapter2/gdp_per_capita.csv')
female_completion_rate = read_csv('../data/chapter2/female_completion_rate.csv')
male_completion_rate = read_csv('../data/chapter2/male_completion_rate.csv')

In [3]:
import pandas as pd

pd.DataFrame(employment_levels[0:3])

Country           1991           1992           1993           1994  \
0  Afghanistan  56.7000007629           56.5  56.5999984741  56.2000007629   
1      Albania  52.7000007629  52.2999992371  52.4000015259  52.7000007629   
2      Algeria  39.4000015259  38.9000015259  39.4000015259  39.4000015259   

            1995           1996           1997           1998           1999  \
0  56.2000007629  56.0999984741  56.2000007629  56.2000007629  56.0999984741   
1  52.7999992371  52.5999984741  52.4000015259  52.0999984741  52.0999984741   
2  38.0999984741  38.9000015259  39.7000007629           39.5  39.4000015259   

            2000           2001           2002           2003           2004  \
0  56.0999984741           56.5  56.4000015259  54.4000015259             56   
1  51.9000015259  51.7999992371  51.7999992371  51.7999992371  51.7000007629   
2  38.5999984741  40.4000015259           41.5  42.7999992371  46.4000015259   

   2005           2006           2007  
0    54             56  55.7000007629  
1  51.5  51.4000015259  51.4000015259  
2    48             50           50.5

In [4]:
pd.DataFrame(life_expectancy[0:3])

Country     1800           1801           1802      1803  \
0  Afghanistan   28.211  28.2007533333  28.1905066667  28.18026   
1      Albania     35.4           35.4           35.4      35.4   
2      Algeria  28.8224        28.8224        28.8224   28.8224   

            1804           1805      1806           1807           1808  ...   \
0  28.1700133333  28.1597666667  28.14952  28.1392733333  28.1290266667  ...    
1           35.4           35.4      35.4           35.4           35.4  ...    
2        28.8224        28.8224   28.8224        28.8224        28.8224  ...    

   2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  
0  52.5  52.9  53.2  53.6    54  54.5  54.8  55.2  55.5  56.2  
1  74.4  74.4  74.5  74.7  74.9    75  75.2  75.5  75.7  75.8  
2  74.2  74.5  74.8    75  75.3  75.6  75.9  76.1  76.2  76.3  

[3 rows x 206 columns]

In [5]:
pd.DataFrame(gdp_per_capita[0:3])

Country 1960 1961 1962 1963 1964 1965 1966 1967 1968 ...   \
0               Abkhazia                                              ...    
1            Afghanistan                                              ...    
2  Akrotiri and Dhekelia                                              ...    

  2002 2003 2004 2005 2006 2007 2008 2009 2010 2011  
0                                                    
1                                                    
2                                                    

[3 rows x 53 columns]

In [6]:
pd.DataFrame(female_completion_rate[0:3])

Country 1970 1971 1972 1973     1974 1975 1976     1977  \
0               Abkhazia                                                   
1            Afghanistan                      4.19285            5.14529   
2  Akrotiri and Dhekelia                                                   

      1978 ...  2002 2003 2004      2005 2006 2007 2008 2009 2010 2011  
0          ...                                                          
1  5.91965 ...                  18.74188                                
2          ...                                                          

[3 rows x 43 columns]

In [7]:
pd.DataFrame(male_completion_rate[0:3])

Country 1970 1971 1972 1973      1974 1975 1976      1977  \
0               Abkhazia                                                     
1            Afghanistan                      26.23178            26.73849   
2  Akrotiri and Dhekelia                                                     

       1978 ...  2002 2003 2004     2005 2006 2007 2008 2009 2010 2011  
0           ...                                                         
1  29.07336 ...                  48.3607                                
2           ...                                                         

[3 rows x 43 columns]

ดูจาก table ข้างบนคร่าวๆจะเห็นว่าข้อมูลเป็นสัญญาณ time series 

* มี dimensions คือ ประเทศต่างๆทั่วโลก
* มี metric คือ ปริมาณตามชื่อ table เลย

เมื่อพิจารณาดูเรามีคำถามในใจดังนี้
1. correlation between employment_levels with life_expectancy
2. correlation between gdp_per_capita with life_expectancy
3. correlation between gdp_per_capita with employment_levels
4. prime time of the world (Highest employment_levels, gdp_per_capita)
5. bad time of the world (lowest employment_levels, gdp_per_capita)
6. correlation between employment_levels with male/female_completion_rate
7. male VS female_completion_rate
8. เราสามารถ predict employment_levels จากข้อมูลอะไรได้

$\dots$

# 3 One-Dimensional Data In NumPy And Pandas
เปรียบเทียบการ unique 

สมมติ get ข้อมูลจากไฟล์ CSV แล้ว

In [13]:
import unicodecsv

#read data from CSV file and make it to lists
def read_csv(filename):
    with open(filename, 'rb') as f:
        reader = unicodecsv.DictReader(f)
        return list(reader)
    
daily_engagement  = read_csv('../data/chapter1/daily_engagement.csv')

ถ้าจะเอา account_key ของ unique student อาจจะต้องทำฟังก์ชั่นแบบนี้

In [14]:
def get_unique_student(data):
    unique_students = set()
    for data_point in data:
        unique_students.add(data_point['acct'])
    return unique_students

unique_engagement_students = get_unique_student(daily_engagement)
len(unique_engagement_students)

1237

ซึ่งช้า และยุ่งยาก มีวิธีที่ง่ายและ performance ดีกว่านี้

In [15]:
import pandas as pd
daily_engagement = pd.read_csv('../data/chapter1/daily_engagement.csv')

In [16]:
len(daily_engagement['acct'].unique())

1237

# Q4 : NumPy Arrays

## One-dimensional data structures
**Pandas**
- Series(more features) *built on Array of NumPy* 

**NumPy (Numerical Python)**
- Array (Simpler)

## NumPy Arrays VS Python lists
** Similarities **
- Access elements by position `a[0]` 
- Access a range of elements `a[1:3]`
- use loops `for x in a:`

**Differences(ที่ NumPy เป็น)**
- Each element should have same type (string, int, boolean, etc)
- Convenient functions `mean()`, `std()`
- can be multi-dimensional


In [69]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Change False to True for each block of code to see what it does

# Accessing elements
if False:
    print(countries[0])
    print(countries[3])

# Slicing
if False:
    print(countries[0:3])
    print(countries[:3])
    print(countries[17:])
    print(countries[:])

# Element types
if False:
    print(countries.dtype)
    print(employment.dtype)
    print(np.array([0, 1, 2, 3]).dtype)
    print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)
    print(np.array([True, False, True]).dtype)
    print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

# Looping
if False:
    for country in countries:
        print('Examining country {}'.format(country))

    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        print('Country {} has employment {}'.format(country,
                country_employment))

# Numpy functions
if False:
    print(employment.mean())
    print(employment.std())
    print(employment.max())
    print(employment.sum())

# เราทำ
def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    
    max_value   = employment.max()   
    maxindex    = np.where(employment==max_value)
    max_country = countries[maxindex]

    return (max_country, max_value)

# เฉลย
def max_employment2(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    maxindex = employment.argmax()   

    return (countries[maxindex],employment[maxindex])

In [70]:
print(max_employment(countries,employment))

(array(['Angola'],
      dtype='<U22'), 75.699996949999999)


In [71]:
print(max_employment2(countries,employment))

('Angola', 75.699996949999999)


# 5 Q : Vectorized Operations

A vector is a list of numbers ใน linear algebra เรียกว่า vector

ถ้า 

A = [1 2 3]

B = [4 5 6]

**A+B = [5 7 9] *(call "vector addition" in linear algebra and NumPy)***

A+B = [1 2 3 4 5 6] *(call "List concatenation" in Python)*

# 6 Q : Multiplying By A Scalar

[1 2 3] x 3 = ?

**My Ans** [3 6 9]

### Python
**Output :** [1 2 3 1 2 3 1 2 3]

### Linear algebra and NumPy
**Output :** [3 6 9]

# 7 Q : Calculate Overall Completion Rate

ใน NumPy สามารถใช้สัญลักษณ์เหล่านี้ดำเนินการกับ vector 2 ตัวได้

#### Math Operations
- Add : +
- Subtract : -
- Multiply : *
- Divide: /
- Exponentiate : **

#### Logical Operations
- And : & 
- Or : |
- Not : ~

make sure your array contain booleans!

#### Comparisson Operations
- Greater: >
- Greater or equal: >=
- Less: < 
- Less or equal: <=
- Equal: == 
- Not Equal: !=

In [88]:
import numpy as np

# Change False to True for each block of code to see what it does

# Arithmetic operations between 2 NumPy arrays
if False:
    a = np.array([1, 2, 3, 4])
    b = np.array([1, 2, 1, 2])
    
    print(a + b)
    print(a - b)
    print(a * b)
    print(a / b)
    print(a ** b)
    
# Arithmetic operations between a NumPy array and a single number
if False:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print(a + b)
    print(a - b)
    print(a * b)
    print(a / b)
    print(a ** b)
    
# Logical operations with NumPy arrays
if False:
    a = np.array([True, True, False, False])
    b = np.array([True, False, True, False])
    
    print(a & b)
    print(a | b)
    print(~a)
    
    print(a & True)
    print(a & False)
    
    print(a | True)
    print(a | False)
    
# Comparison operations between 2 NumPy Arrays
if False:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([5, 4, 3, 2, 1])
    
    print(a > b)
    print(a >= b)
    print(a < b)
    print(a <= b)
    print(a == b)
    print(a != b)
    
# Comparison operations between a NumPy array and a single number
if False:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print(a > b)
    print(a >= b)
    print(a < b)
    print(a <= b)
    print(a == b)
    print(a != b)
    
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    all_completion = (female_completion+male_completion)/2.
    return all_completion

# 8 Q : Standardizing Data
ปริมาณของข้อมูล ดูเฉยๆมองไม่เห็นภาพว่าเยอะหรือน้อย หรือ...? 

ถ้าอยากเห็นภาพว่าข้อมูลเป็นยังไง วิธีการที่นิยมอย่างหนึ่งคือ 
- หา mean ของชุดข้อมูล
- หาดูว่าแต่ละค่าห่างจาก mean คิดเป็นกี่เท่าของ SD

ในโปรเจคนี้จะพิจารณา number of SD away from mean ของ employment rate

ตย. จากปี 2007,
- mean employment rate: 58.6%
- standard deviation: 10.5%
- United States: 62.3%
- Mexico: 57.9%

US ได้ 
- diff: 3.7% or 0.35SD

Mexico ได้
- diff: -0.7% or 0.067SD


In [98]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Change this country name to change what country will be printed when you
# click "Test Run". Your function will be called to determine the standardized
# score for this country for each of the given 5 Gapminder variables in 2007.
# The possible country names are available in the Downloadables section.

country_name = 'United States'

def standardize_data(values):
    '''
    Fill in this function to return a standardized version of the given values,
    which will be in a NumPy array. Each value should be translated into the
    number of standard deviations that value is away from the mean of the data.
    (A positive number indicates a value higher than the mean, and a negative
    number indicates a value lower than the mean.)
    '''
    mean = values.mean()
    std = values.std()
    diff = values - mean
    standardize_data = diff/std
    
    return standardize_data

In [99]:
standardize_data(employment)

array([-0.31965231, -0.780123  , -0.87650077,  1.82207181, -0.03051941,
       -1.99019768,  0.30144772, -0.16973184,  0.23719615,  0.84758731,
        0.18365304,  1.00821665,  0.87971351, -0.56595055, -1.07996476,
       -0.20185762,  1.38301845, -0.03051941,  1.2545153 , -1.87240259])

# 9 Q : NumPy Index Arrays

ถ้าเรามี array 2 อันที่ยาวเท่ากัน แล้วอันที่ 2 เป็น Booleans

a = [1 2 3 4 5]

b = [F F T T T] หรือ b = a > 2

จะได้

a[b] = a[a>2] = [3 4 5]


In [106]:
import numpy as np

# Change False to True for each block of code to see what it does

# Using index arrays
if False:
    a = np.array([1, 2, 3, 4])
    b = np.array([True, True, False, False])
    
    print(a[b])
    print(a[np.array([True, False, True, False])])
    
# Creating the index array using vectorized operations
if False:
    a = np.array([1, 2, 3, 2, 1])
    b = (a >= 2)
    
    print(a[b])
    print(a[a >= 2])
    
# Creating the index array using vectorized operations on another array
if False:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1, 2, 3, 2, 1])
    
    print(b == 2)
    print(a[b == 2])

def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    stayed_at_least_7_day = (days_to_cancel >= 7)
    mean_time_spent = time_spent[stayed_at_least_7_day].mean()
    return mean_time_spent

# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

mean_time_for_paid_students(time_spent, days_to_cancel)

41.054003485454537

# 10 Q : + Vs. +=



In [109]:
import numpy as np
a = np.array([1,2,3,4])
b = a
a+= np.array([1,1,1,1])
print(b)

[2 3 4 5]


In [110]:
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1])
print(b)

[1 2 3 4]


ตัวล่างค่า b ไม่เปลี่ยนตามเพราะ a = a + np.array([1,1,1,1]) คือมีแค่ a เท่านั้นที่เปลี่ยนไปชี้หา array ใหม่ แต่ก้อนบนคือ a และ b ชี้ไปที่อาเรย์เดียวกันเหมือนเดิม พออาเรย์นั้นค่าเพิ่ม b ก็เปลี่ยนค่าตามด้วย (เครื่องหมาย = คือตัวระบุการชี้ค่าตัวแปรใหม่)

# 11 Q : In-Place Vs. Not In-Place

**+=** operates in-place while **+** does not 

**"Operation that are not in-place are much easier to think about!"**

ใช้แบบ a = a+5 ดีกว่า เพราะเข้าใจง่ายกว่า ไม่เปลี่ยนค่าตั้งต้น อ่านง่าน ตาม code ง่ายกว่ามาก ในขณะที่ a+=5 นั้น จะเปลี่ยนค่าตั้งต้น ทำให้ตัวแปรอื่นที่ใช้ค่า a จะเปลี่ยนตามด้วย

In [117]:
a = np.array([1,2,3,4,5])
Slice = a[:3]
Slice[0] = 100
print(a)

[100   2   3   4   5]


NumPy ไม่ create array ใหม่ แต่ชี้ไปที่ array ตัวแปรต้นแทน ดังนั้นค่า a จึงเปลี่ยนด้วย

# 12 Q : Pandas Series
Python เรียก list

NumPy เรียก Array

Pandas เรียก Series แต่ทั้งหมดเป็นอย่างเดียวกัน

**"Numpy และ Pandas เร็วกว่า Python เพราะมัน implement บน C"**

A series is similar to a NumPy array, but with extra functionality

e.g. s.describe()

#### Similarities
- access elements s[0], s[3:7]
- Looping for x in s
- convinient functions s.mean(), s.max()
- vectorized operation s1+s2
- Implement in C (fast!)



In [20]:
import pandas as pd

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

# Change False to True for each block of code to see what it does

# Accessing elements and slicing
if False:
    print(life_expectancy[0])
    print(gdp[3:6])
    
# Looping
if False:
    for country_life_expectancy in life_expectancy:
        print('Examining life expectancy {}'.format(country_life_expectancy))
        
# Pandas functions
if False:
    print(life_expectancy.mean())
    print(life_expectancy.std())
    print(gdp.max())
    print(gdp.sum())

# Vectorized operations and index arrays
if False:
    a = pd.Series([1, 2, 3, 4])
    b = pd.Series([1, 2, 1, 2])
  
    print(a + b)
    print(a * 2)
    print(a >= 3)
    print(a[a >= 3])
   
def variable_correlation(variable1, variable2):
    '''
    Fill in this function to calculate the number of data points for which
    the directions of variable1 and variable2 relative to the mean are the
    same, and the number of data points for which they are different.
    Direction here means whether each value is above or below its mean.
    
    You can classify cases where the value is equal to the mean for one or
    both variables however you like.
    
    Each argument will be a Pandas series.
    
    For example, if the inputs were pd.Series([1, 2, 3, 4]) and
    pd.Series([4, 5, 6, 7]), then the output would be (4, 0).
    This is because 1 and 4 are both below their means, 2 and 5 are both
    below, 3 and 6 are both above, and 4 and 7 are both above.
    
    On the other hand, if the inputs were pd.Series([1, 2, 3, 4]) and
    pd.Series([7, 6, 5, 4]), then the output would be (0, 4).
    This is because 1 is below its mean but 7 is above its mean, and
    so on.
    '''
    # function ที่เชค direction(มากหรือน้อยกว่า mean) ของสอง set ว่าเหมือนกันกี่ตัวหรือต่างกันกี่ตัว
    above_mean1 = (variable1 > variable1.mean()) 
    above_mean2 = (variable2 > variable2.mean())
    
    num_same_direction = (above_mean1 == above_mean2).sum()        # Replace this with your code
    num_different_direction = (above_mean1 != above_mean2).sum()    # Replace this with your code
    
    return (num_same_direction, num_different_direction)

In [21]:
variable_correlation(life_expectancy, gdp)

(17, 3)

# 13 Q : Series Indexes
ความต่างระหว่าง numpy array และ panda series

นอกจากฟังก์ชั่น describe แล้ว panda นั้นมี index เป็น key ได้คล้ายๆ dict ของ python

ถ้าบอกว่า numpy เป็นขั้นกว่าของ python list pandas ก็เป็นอีกขั้นของ numpy คือ ประเภทข้อมูลของ numpy มีได้อย่างเดียว ถ้าค่าเป็น float แล้ว ไม่สามารถเอาคีย์มาเป็น string ได้แต่ pandas ทำได้

In [23]:
import numpy as np
import pandas as pd

a = np.array([1,2,3,4])
s = pd.Series([1,2,3,4])
s.describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [25]:
life_expectancy = pd.Series([9,8,7,6],index=['A','B','C','D'])
life_expectancy

A    9
B    8
C    7
D    6
dtype: int64

In [46]:
import pandas as pd

countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]

# Employment data in 2007 for 20 countries
employment = pd.Series(employment_values, index=countries)

def max_employment(employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    
    The input will be a Pandas series where the values
    are employment and the index is country names.
    
    Try using the Pandas idxmax() function. Documention can
    be found here:
    http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.idxmax.html
    '''
    
    max_country = employment.idxmax()      # Replace this with your code
    max_country = employment.argmax()      
    max_value = employment.loc[max_country]   # Replace this with your code

    return (max_country, max_value)

In [47]:
employment[0]

55.700000760000002

In [48]:
employment.iloc[0]

55.700000760000002

In [49]:
employment.loc['Bhutan']

58.400001529999997

In [50]:
max_employment(employment)

('Angola', 75.699996949999999)